### ISSUE TITLE
Support latest version of D3

### ISSUE THREAD

**Issue by nghuuphuoc** [spaced/scala-js-d3#13]
Currently, I can't use the latest version of D3 (3.5.12 at the moment):

```
// built.sbt
jsDependencies += "org.webjars" % "d3js" % "3.5.12" / "3.5.12/d3.min.js"
```

The compilation tells me about the conflict that the current facade is compatible with D3 3.5.6 only.

**Comment by spaced** [comment]
latest webjar seams to be 3.5.10, i can lift it to this version. https://github.com/webjars/d3js

**Comment by nghuuphuoc** [comment]
Thanks :+1:

**Comment by nghuuphuoc** [comment]
I tried to change my built configuration file to use d3 3.5.10:

```
jsDependencies += "org.webjars" % "d3js" % "3.5.10" / "3.5.10/d3.min.js"
```

but the IDE informs the error

```
Error:Error while importing SBT project:
...
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

[error] org.apache.ivy.plugins.conflict.StrictConflictException: org.webjars#d3js;3.5.6 
(needed by [org.singlespaced#scalajs-d3_sjs0.6_2.11;0.1.2]) 
conflicts with org.webjars#d3js;3.5.10 
(needed by [com.xxx.xxx#xxx_sjs0.6_2.11;0.5.0-MVP-986-g266d890-SNAPSHOT])
[error] Use 'last' for the full log.

See complete log in /Users/phuocnguyen/Library/Logs/IntelliJIdea14/sbt.last.log
```

You can take a look at the conflict message at the bottom.

**Comment by spaced** [comment]
expected behavior: you can not depend same libs with different versions.
you can override jsDependencies with

```
jsDependencies = "org.webjars" % "d3js" % "3.5.10" / "3.5.10/d3.min.js"
```

as workaround until new version is available.
